<script setup>
import { ref, onMounted } from "vue";
import { codeToHtml } from "shiki";

const props = defineProps({
  scriptPath: {
    type: String,
    required: true,
  },
});

const files = ref([]);
const loading = ref(true);
const error = ref(null);
const highlightedBlocks = ref({});
const newConfigFormat = ref(false);
const scriptName = ref("");

async function fetchConfig() {
  loading.value = true;
  error.value = null;
  try {
    const res = await fetch(
      `https://jumpon-studios.com/api/scripts/config/${props.scriptPath}`,
    );
    const data = await res.json();
    console.log("Fetched config data:", data);
    if (data.success && data.files) {
      files.value = data.files;
      newConfigFormat.value = data.files.some((file) =>
        file.path.includes("_default.lock"),
      );
      scriptName.value = data.files[0].path.split("/")[0];
      await highlightAll(data.files);
    } else {
      error.value = "Failed to load configuration files.";
    }
  } catch (e) {
    error.value = "Failed to fetch configuration.";
  } finally {
    loading.value = false;
  }
}

async function highlightAll(fileList) {
  const results = {};
  await Promise.all(
    fileList.map(async (file, index) => {
      results[index] = await codeToHtml(file.content, {
        lang: "lua",
        themes: {
          light: "light-plus",
          dark: "slack-dark",
        },
        defaultColor: false,
      });
    }),
  );
  highlightedBlocks.value = results;
}

function copyCode(content) {
  navigator.clipboard.writeText(content);
}

onMounted(() => {
  fetchConfig();
});
</script>

<template>
  <div v-if="newConfigFormat">
    <p>
      The configuration files are located in the
      <code>config</code>
      folder within the resource. This folder contains two subfolders:
    </p>
    <ul>
      <li>
        <strong><code>_default.lock/</code></strong>
        - Contains the default configuration files.
        <strong>Do not edit these files directly</strong>
        as they may be overwritten during updates.
      </li>
      <li>
        <strong><code>custom/</code></strong>
        - This is where you place your custom configuration files to override
        the defaults.
      </li>
    </ul>
    <h3 id="how-to-customize-the-configuration" tabindex="-1">
      How to customize the configuration
      <a
        class="header-anchor"
        href="#how-to-customize-the-configuration"
        aria-label="Permalink to “How to customize the configuration”"
      >
        &ZeroWidthSpace;
      </a>
    </h3>
    <ol>
      <li>
        Navigate to
        <code>{{ scriptName }}/config/_default.lock/</code>
      </li>
      <li>
        Copy the file you want to modify (e.g.,
        <code>prices.lua</code>
        )
      </li>
      <li>
        Paste it into
        <code>{{ scriptName }}/config/custom/</code>
      </li>
      <li>
        Edit the copied file in the
        <code>custom</code>
        folder
      </li>
    </ol>
    <p>
      The script automatically loads files from
      <code>custom/</code>
      first, and only uses
      <code>_default.lock/</code>
      as a fallback. This system ensures your customizations are preserved when
      updating the script.
    </p>

    <h3 id="default-configuration-files" tabindex="-1">
      Default configuration files
      <a
        class="header-anchor"
        href="#default-configuration-files"
        aria-label="Permalink to “Default configuration files”"
      >
        ​
      </a>
    </h3>
  </div>
  <div v-else>
    <p>
      The configuration file is
      <code>config.lua</code>
      in the resource root.
      <strong>Do not edit this file directly</strong>
      as your changes may be lost during updates. Instead, use
      <code>overwriteConfig.lua</code>
      to store your customizations.
    </p>
    <ul>
      <li>
        <strong><code>config.lua</code></strong>
        - Default configuration maintained by developers.
        <strong>Do not modify this file.</strong>
      </li>
      <li>
        <strong><code>overwriteConfig.lua</code></strong>
        - This is where you place only the values you want to override.
      </li>
    </ul>
    <h3 id="how-to-customize-the-configuration" tabindex="-1">
      How to customize the configuration
      <a
        class="header-anchor"
        href="#how-to-customize-the-configuration"
        aria-label='Permalink to "How to customize the configuration"'
      >
        &ZeroWidthSpace;
      </a>
    </h3>
    <ol>
      <li>
        Open
        <code>{{ scriptName }}/overwriteConfig.lua</code>
      </li>
      <li>
        Find the value you want to change in
        <code>config.lua</code>
        (e.g.,
        <code>Config.language</code>
        )
      </li>
      <li>
        Copy only that line into
        <code>overwriteConfig.lua</code>
      </li>
      <li>Edit the copied value to your liking</li>
    </ol>
    <p>
      The script loads
      <code>config.lua</code>
      first, then
      <code>overwriteConfig.lua</code>
      overwrites only the values you redefine. This ensures your customizations
      are preserved when updating the script.
    </p>
  </div>

  <div v-if="loading" class="sc-loading-wrapper">
    <div class="sc-loading">
      <div class="sc-spinner"></div>
      <span>Loading configuration...</span>
    </div>
  </div>

  <div v-else-if="error" class="sc-error">{{ error }}</div>

  <div v-else-if="files.length" class="vp-code-group">
    <div class="tabs">
      <template v-for="(file, index) in files" :key="index">
        <input
          type="radio"
          :name="`sc-group-${scriptPath}`"
          :id="`sc-tab-${scriptPath}-${index}`"
          :checked="index === 0"
        />
        <label :for="`sc-tab-${scriptPath}-${index}`">
          {{ file.fileName }}
        </label>
      </template>
    </div>
    <div class="blocks">
      <div
        v-for="(file, index) in files"
        :key="index"
        class="language-lua vp-adaptive-theme"
        :class="{ active: index === 0 }"
      >
        <button
          class="copy"
          @click="copyCode(file.content)"
          title="Copy"
        ></button>
        <span class="lang">lua</span>
        <div v-html="highlightedBlocks[index]" class="vp-code"></div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.sc-loading-wrapper {
  margin-top: 16px;
}

.sc-loading {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 24px;
  color: var(--vp-c-text-2);
  font-size: 14px;
  background-color: var(--vp-code-block-bg);
  border-radius: 8px;
}

.sc-spinner {
  width: 20px;
  height: 20px;
  border: 2px solid var(--vp-c-border);
  border-top-color: var(--vp-c-brand-1);
  border-radius: 50%;
  animation: sc-spin 0.6s linear infinite;
}

@keyframes sc-spin {
  to {
    transform: rotate(360deg);
  }
}

.sc-error {
  margin-top: 16px;
  padding: 24px;
  color: var(--vp-c-danger-1);
  font-size: 14px;
  background-color: var(--vp-code-block-bg);
  border-radius: 8px;
}
</style>
